site_name: "PyBots - Devkit for quickly creating client bots for remote communications"
repo_url: https://github.com/dhondta/python-pybots
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - Features: features.md
  - Using Bots: usage.md
  - Creating Bots: create.md
  - Examples:
    - 'Hackvent 2017': examples/hackvent-2017.md
    - 'RingZer0': examples/ringzer0.md
    - 'Root-Me': examples/rootme.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: true
